# Numpy Assignment

### 1. Waht is a python library? why do we use python libraries?
### Ans. A library is a collection of code that makes everyday tasks more efficient.
 ###    Python libraries are used to create applications and models in a variety of fields, for instance, machine learning, data science, data visualization, image and data manipulation, and many more.

### 2. What is the diffrance between Numpy array and list? 
 ### Ans. Array can store only similar data types, List can store more than one data type

In [1]:
import numpy as np

### 3 Find the shape, size and dimension of the following array
### [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [3]:


arr1 =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
#Dimension 
print(arr1.ndim)
#Shape
print(arr1.shape)
#Size
print(arr1.size)

2
(3, 4)
12


### 4 Write python code to access the first row of the following array
### [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [5]:
first_row =arr1[0]
print(first_row)

[1 2 3 4]


### 5 How do you access the element at the third row and forth column from the given numpy array
### [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [6]:
elements = arr1[2,3]
print(elements)

12


### 6 Write the code to extract all odd-indexed elements from the given numpy array
### [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [7]:
odd_indexedElements = arr1[:, 1::2]
print(odd_indexedElements)

[[ 2  4]
 [ 6  8]
 [10 12]]


### 7 How can you generate a random 3x3 matrix with values between 0 and 1

In [10]:
a = np.random.rand(3,3)
print(a)

[[0.55788658 0.0362425  0.71916698]
 [0.58658721 0.91554516 0.01565453]
 [0.16749961 0.18927067 0.8880214 ]]


### 8 Describe the diffrance between np.random.rand and np.random.randn
### "np.random.rand" generates random numbers from a uniform distribution between 0 and 1 
### "np.random.randn" generates random numbers from a standard normal distribution with mean 0 and standard deviation 1.

### 9  Write code to increase the dimension of the following array ?
### [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [5]:
import numpy as np 
arr1 =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
new_arr = np.expand_dims(arr1, axis=0)
print(new_arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


### 10 How to transpose the following array in Numpy?
### [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [6]:
a = np.transpose(arr1)
print(a)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### 11 Consider the following matrix:
### Matrix A: [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
### Matrix B: [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
### Perform the following operations using python

### 1. Index wise multiplication

In [7]:
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
B = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

p = A*B
print(p)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


### 2. Matrix Multiplication

In [8]:
q = np.dot(A,B.T)
print(q)

[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


### 3. Add both matrices

In [9]:
r = A +  B
print(r)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


### 4. Substract matrix B from A

In [11]:
s = A - B
print(s)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### 5. Divide Matrix B by A

In [12]:
t = B/A
print(t)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 12 Which function in Numpy can be used to swap the byte order of an array?
### Ans. "byteswap"

### 13 What is the significance of the np.linalg.inv function?
### Ans. The function "np.linalg.inv" is used to calculate inverse of a square matrix

### 14 What dose the np.reshape function do, and how is it used?
### Ans. reshape function is used to change the dimension or change number of elements in each dimension.

In [13]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
New_arr2 = arr2.reshape(4,3)
print(New_arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### 15 What is broadcasting in Numpy?
### Ans. The term broadcasting describe how NumPy treats array with different shapes during arithmetic operations.